In [1]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [2]:
print(x)

tensor([1., 1., 1., 1., 1.])


In [3]:
print(y)

tensor([0., 0., 0.])


In [4]:
print(w)

tensor([[ 0.8253, -0.7900, -0.6300],
        [ 0.9437,  1.6949, -0.0392],
        [-0.1646,  1.2154, -1.9673],
        [-1.9810, -0.0744, -0.9108],
        [ 1.2825, -0.4294, -0.2078]], requires_grad=True)


In [5]:
print(b)

tensor([ 0.5942, -0.6536,  0.5854], requires_grad=True)


In [6]:
print(z)

tensor([ 1.5001,  0.9629, -3.1697], grad_fn=<AddBackward0>)


In [7]:
print(loss)

tensor(1.0096, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [8]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x000001CA14D3A980>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001CA4FD968C0>


In [9]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.2725, 0.2412, 0.0134],
        [0.2725, 0.2412, 0.0134],
        [0.2725, 0.2412, 0.0134],
        [0.2725, 0.2412, 0.0134],
        [0.2725, 0.2412, 0.0134]])
tensor([0.2725, 0.2412, 0.0134])


In [10]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [11]:
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


In [12]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


In [13]:
print(out)

tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)


In [15]:
torch.ones_like(out)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
print(inp)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)
