In [1]:
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


## Create a tensor directly from a datalist
**Tensors can be created directly from data. The data type is automatically inferred.**

In [2]:
data = [[1,2],[3,4]]
data_tensor = torch.tensor(data)

print(data_tensor)

tensor([[1, 2],
        [3, 4]])


## Create a tensor from a NumPy array
**Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).**

In [3]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)

print(data_tensor)

tensor([[5, 6],
        [7, 8]])


## Create a tensor with same properties (shape, datatype) of an argument tensor

In [4]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)


# A tensor of the same shape as data_tensor with a 1 as every element
ones_tensor = torch.ones_like(data_tensor) # retains the properties of x_data
print(f"Ones Tensor: \n {ones_tensor} \n")

# A tensor of the same shape as data_tensor with a random number as every element
random_tensor = torch.rand_like(data_tensor, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {random_tensor} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5929, 0.3876],
        [0.1584, 0.3744]]) 



## Create a tensor with random or constant values
**shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.**

In [5]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1776, 0.4826, 0.6514],
        [0.1626, 0.5392, 0.3943]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Commands to see tensor attributes
**Tensor attributes describe their shape, datatype, and the device on which they are stored.**

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Commands to move tensor to GPU

In [7]:
tensor = torch.rand(3,4)

if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


## Indexing/Slicing commands

In [10]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
print(tensor)

tensor[:,1] = 0
print(tensor)

First row: tensor([0.6010, 0.7525, 0.6413, 0.9506])
First column: tensor([0.6010, 0.8664, 0.7987, 0.1023])
Last column: tensor([0.9506, 0.9574, 0.0271, 0.1681])
tensor([[0.6010, 0.7525, 0.6413, 0.9506],
        [0.8664, 0.0714, 0.0065, 0.9574],
        [0.7987, 0.0458, 0.7313, 0.0271],
        [0.1023, 0.0724, 0.1646, 0.1681]])
tensor([[0.6010, 0.0000, 0.6413, 0.9506],
        [0.8664, 0.0000, 0.0065, 0.9574],
        [0.7987, 0.0000, 0.7313, 0.0271],
        [0.1023, 0.0000, 0.1646, 0.1681]])


## Concatenate tensors
**You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining operator that is subtly different from torch.cat.**

In [11]:
tensor1 = torch.tensor([[1,1],[1,1]])
tensor2 = torch.tensor([[2,2],[2,2]])
print(tensor1)
print(tensor2)

#concatenate tensors along the rows (it stacks them vertically)
tensor4x2 = torch.cat([tensor1,tensor2], dim=0)
print(tensor4x2)

#concatenate tensors along the columns (combine them horizontally)
tensor2x4 = torch.cat([tensor1,tensor2], dim=1)
print(tensor2x4)

tensor([[1, 1],
        [1, 1]])
tensor([[2, 2],
        [2, 2]])
tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2]])
tensor([[1, 1, 2, 2],
        [1, 1, 2, 2]])


## Operations on tensors

### Matrix multiplication between tensor and its transpose

In [12]:
tensor = torch.rand(4, 4)
print(tensor)

tensor([[0.4610, 0.0301, 0.2175, 0.9851],
        [0.4656, 0.3537, 0.5443, 0.8283],
        [0.4644, 0.3030, 0.1562, 0.8003],
        [0.4535, 0.8802, 0.7383, 0.7389]])


In [13]:
transpose_tensor = tensor.T
print(transpose_tensor)

tensor([[0.4610, 0.4656, 0.4644, 0.4535],
        [0.0301, 0.3537, 0.3030, 0.8802],
        [0.2175, 0.5443, 0.1562, 0.7383],
        [0.9851, 0.8283, 0.8003, 0.7389]])


In [14]:
y1 = tensor @ transpose_tensor
print(y1)

tensor([[1.2311, 1.1597, 1.0455, 1.1240],
        [1.1597, 1.3244, 1.0713, 1.5365],
        [1.0455, 1.0713, 0.9723, 1.1840],
        [1.1240, 1.5365, 1.1840, 2.0716]])


In [15]:
y2 = tensor.matmul(tensor.T)
print(y2)

tensor([[1.2311, 1.1597, 1.0455, 1.1240],
        [1.1597, 1.3244, 1.0713, 1.5365],
        [1.0455, 1.0713, 0.9723, 1.1840],
        [1.1240, 1.5365, 1.1840, 2.0716]])


In [16]:
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[0.6665, 0.0221, 0.9016, 0.7512],
        [0.6389, 0.3740, 0.9926, 0.2296],
        [0.1402, 0.3277, 0.0350, 0.2825],
        [0.2529, 0.2678, 0.6202, 0.7424]])
tensor([[1.2311, 1.1597, 1.0455, 1.1240],
        [1.1597, 1.3244, 1.0713, 1.5365],
        [1.0455, 1.0713, 0.9723, 1.1840],
        [1.1240, 1.5365, 1.1840, 2.0716]])


**y1, y2, and y3 are mathematically equivalent operations**

### Element-wise product between tensor and itself

In [17]:
print(tensor)
z1 = tensor * tensor
print(z1)

tensor([[0.4610, 0.0301, 0.2175, 0.9851],
        [0.4656, 0.3537, 0.5443, 0.8283],
        [0.4644, 0.3030, 0.1562, 0.8003],
        [0.4535, 0.8802, 0.7383, 0.7389]])
tensor([[2.1256e-01, 9.0302e-04, 4.7303e-02, 9.7033e-01],
        [2.1682e-01, 1.2513e-01, 2.9630e-01, 6.8615e-01],
        [2.1563e-01, 9.1817e-02, 2.4392e-02, 6.4049e-01],
        [2.0568e-01, 7.7484e-01, 5.4506e-01, 5.4602e-01]])


In [18]:
z2 = tensor.mul(tensor)
print(z2)

tensor([[2.1256e-01, 9.0302e-04, 4.7303e-02, 9.7033e-01],
        [2.1682e-01, 1.2513e-01, 2.9630e-01, 6.8615e-01],
        [2.1563e-01, 9.1817e-02, 2.4392e-02, 6.4049e-01],
        [2.0568e-01, 7.7484e-01, 5.4506e-01, 5.4602e-01]])


In [19]:
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[0.4846, 0.5131, 0.2745, 0.4072],
        [0.2903, 0.1147, 0.7906, 0.8210],
        [0.7524, 0.0712, 0.4722, 0.5068],
        [0.0725, 0.0339, 0.7480, 0.6309]])
tensor([[2.1256e-01, 9.0302e-04, 4.7303e-02, 9.7033e-01],
        [2.1682e-01, 1.2513e-01, 2.9630e-01, 6.8615e-01],
        [2.1563e-01, 9.1817e-02, 2.4392e-02, 6.4049e-01],
        [2.0568e-01, 7.7484e-01, 5.4506e-01, 5.4602e-01]])


**z1, z2, and z3 are mathematically equivalent operations**

### Aggregate all values of a tensor into one value
**If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item()**

In [20]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(8.4205)
8.420516967773438 <class 'float'>


### In-place operations
**Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.**

In [21]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.4610, 0.0301, 0.2175, 0.9851],
        [0.4656, 0.3537, 0.5443, 0.8283],
        [0.4644, 0.3030, 0.1562, 0.8003],
        [0.4535, 0.8802, 0.7383, 0.7389]]) 

tensor([[5.4610, 5.0301, 5.2175, 5.9851],
        [5.4656, 5.3537, 5.5443, 5.8283],
        [5.4644, 5.3030, 5.1562, 5.8003],
        [5.4535, 5.8802, 5.7383, 5.7389]])


## Bridge tensor with NumPy
**Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.**

In [22]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [23]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**there was an immediate change in n because t and n share memory**

In [24]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**there was an immediate change in t because t and n share memory**