In [5]:
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

## Create a tensor directly from a datalist

In [8]:
data = [[1,2],[3,4]]
data_tensor = torch.tensor(data)

print(data_tensor)

tensor([[1, 2],
        [3, 4]])


## Create a tensor from a NumPy array

In [10]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)

print(data_tensor)

tensor([[5, 6],
        [7, 8]], dtype=torch.int32)


## Create a tensor with same properties (shape, datatype) of an argument tensor

In [14]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)


# A tensor of the same shape as data_tensor with a 1 as every element
ones_tensor = torch.ones_like(data_tensor) # retains the properties of x_data
print(f"Ones Tensor: \n {ones_tensor} \n")

# A tensor of the same shape as data_tensor with a random number as every element
random_tensor = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {random_tensor} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]], dtype=torch.int32) 

Random Tensor: 
 tensor([[0.4840, 0.5734],
        [0.9096, 0.7322]]) 



## Create a tensor with random or constant values

In [22]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3720, 0.3423, 0.1111],
        [0.3384, 0.2419, 0.3038]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Commands to see tensor attributes

In [23]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Commands to move tensor to GPU

In [25]:
tensor = torch.rand(3,4)

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


## Indexing/Slicing commands

In [42]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
print(tensor)

tensor[:,1] = 0
print(tensor)

First row: tensor([0.3525, 0.3297, 0.1329, 0.5187])
First column: tensor([0.3525, 0.7371, 0.5037, 0.8047])
Last column: tensor([0.5187, 0.6101, 0.2881, 0.6268])
tensor([[0.3525, 0.3297, 0.1329, 0.5187],
        [0.7371, 0.7154, 0.1549, 0.6101],
        [0.5037, 0.2112, 0.0457, 0.2881],
        [0.8047, 0.1421, 0.1409, 0.6268]])
tensor([[0.3525, 0.0000, 0.1329, 0.5187],
        [0.7371, 0.0000, 0.1549, 0.6101],
        [0.5037, 0.0000, 0.0457, 0.2881],
        [0.8047, 0.0000, 0.1409, 0.6268]])


## Concatenate tensors

In [61]:
tensor1 = torch.tensor([[1,1],[1,1]])
tensor2 = torch.tensor([[2,2],[2,2]])
print(tensor1)
print(tensor2)

#concatenate tensors along the rows (it stacks them vertically)
tensor4x2 = torch.cat([tensor1,tensor2], dim=0)
print(tensor4x2)

#concatenate tensors along the columns (combine them horizontally)
tensor2x4 = torch.cat([tensor1,tensor2], dim=1)
print(tensor2x4)

tensor([[1, 1],
        [1, 1]])
tensor([[2, 2],
        [2, 2]])
tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2]])
tensor([[1, 1, 2, 2],
        [1, 1, 2, 2]])


## Operations on tensors