In [1]:
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


## Create a tensor directly from a datalist

In [2]:
data = [[1,2],[3,4]]
data_tensor = torch.tensor(data)

print(data_tensor)

tensor([[1, 2],
        [3, 4]])


## Create a tensor from a NumPy array

In [3]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)

print(data_tensor)

tensor([[5, 6],
        [7, 8]])


## Create a tensor with same properties (shape, datatype) of an argument tensor

In [4]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)


# A tensor of the same shape as data_tensor with a 1 as every element
ones_tensor = torch.ones_like(data_tensor) # retains the properties of x_data
print(f"Ones Tensor: \n {ones_tensor} \n")

# A tensor of the same shape as data_tensor with a random number as every element
random_tensor = torch.rand_like(data_tensor, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {random_tensor} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1771, 0.8645],
        [0.1605, 0.9687]]) 



## Create a tensor with random or constant values

In [5]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0521, 0.8854, 0.1744],
        [0.5343, 0.8076, 0.6904]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Commands to see tensor attributes

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Commands to move tensor to GPU

In [7]:
tensor = torch.rand(3,4)

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


## Indexing/Slicing commands

In [8]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
print(tensor)

tensor[:,1] = 0
print(tensor)

First row: tensor([0.3947, 0.0881, 0.9897, 0.7881])
First column: tensor([0.3947, 0.1338, 0.4018, 0.9658])
Last column: tensor([0.7881, 0.3358, 0.9586, 0.9439])
tensor([[0.3947, 0.0881, 0.9897, 0.7881],
        [0.1338, 0.2195, 0.9885, 0.3358],
        [0.4018, 0.1422, 0.0253, 0.9586],
        [0.9658, 0.3164, 0.3476, 0.9439]])
tensor([[0.3947, 0.0000, 0.9897, 0.7881],
        [0.1338, 0.0000, 0.9885, 0.3358],
        [0.4018, 0.0000, 0.0253, 0.9586],
        [0.9658, 0.0000, 0.3476, 0.9439]])


## Concatenate tensors

In [9]:
tensor1 = torch.tensor([[1,1],[1,1]])
tensor2 = torch.tensor([[2,2],[2,2]])
print(tensor1)
print(tensor2)

#concatenate tensors along the rows (it stacks them vertically)
tensor4x2 = torch.cat([tensor1,tensor2], dim=0)
print(tensor4x2)

#concatenate tensors along the columns (combine them horizontally)
tensor2x4 = torch.cat([tensor1,tensor2], dim=1)
print(tensor2x4)

tensor([[1, 1],
        [1, 1]])
tensor([[2, 2],
        [2, 2]])
tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2]])
tensor([[1, 1, 2, 2],
        [1, 1, 2, 2]])


## Operations on tensors

### Matrix multiplication between tensor and its transpose

In [10]:
tensor = torch.rand(4, 4)
print(tensor)

tensor([[0.6854, 0.2610, 0.8810, 0.9391],
        [0.1775, 0.7907, 0.1515, 0.5915],
        [0.4443, 0.6153, 0.6884, 0.7351],
        [0.2971, 0.5484, 0.7459, 0.5980]])


In [11]:
transpose_tensor = tensor.T
print(transpose_tensor)

tensor([[0.6854, 0.1775, 0.4443, 0.2971],
        [0.2610, 0.7907, 0.6153, 0.5484],
        [0.8810, 0.1515, 0.6884, 0.7459],
        [0.9391, 0.5915, 0.7351, 0.5980]])


In [12]:
y1 = tensor @ transpose_tensor
print(y1)

tensor([[2.1961, 1.0170, 1.7620, 1.5655],
        [1.0170, 1.0295, 1.1045, 0.9530],
        [1.7620, 1.1045, 1.5903, 1.4225],
        [1.5655, 0.9530, 1.4225, 1.3029]])


In [13]:
y2 = tensor.matmul(tensor.T)
print(y2)

tensor([[2.1961, 1.0170, 1.7620, 1.5655],
        [1.0170, 1.0295, 1.1045, 0.9530],
        [1.7620, 1.1045, 1.5903, 1.4225],
        [1.5655, 0.9530, 1.4225, 1.3029]])


In [14]:
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[0.1302, 0.6409, 0.1598, 0.4065],
        [0.2963, 0.5083, 0.0074, 0.9520],
        [0.5621, 0.6559, 0.2419, 0.7412],
        [0.3865, 0.1272, 0.5175, 0.8426]])
tensor([[2.1961, 1.0170, 1.7620, 1.5655],
        [1.0170, 1.0295, 1.1045, 0.9530],
        [1.7620, 1.1045, 1.5903, 1.4225],
        [1.5655, 0.9530, 1.4225, 1.3029]])


**y1, y2, and y3 are mathematically equivalent operations**

### Element-wise product between tensor and itself

In [15]:
print(tensor)
z1 = tensor * tensor
print(z1)

tensor([[0.6854, 0.2610, 0.8810, 0.9391],
        [0.1775, 0.7907, 0.1515, 0.5915],
        [0.4443, 0.6153, 0.6884, 0.7351],
        [0.2971, 0.5484, 0.7459, 0.5980]])
tensor([[0.4698, 0.0681, 0.7762, 0.8819],
        [0.0315, 0.6252, 0.0229, 0.3498],
        [0.1974, 0.3786, 0.4739, 0.5404],
        [0.0883, 0.3007, 0.5563, 0.3576]])


In [16]:
z2 = tensor.mul(tensor)
print(z2)

tensor([[0.4698, 0.0681, 0.7762, 0.8819],
        [0.0315, 0.6252, 0.0229, 0.3498],
        [0.1974, 0.3786, 0.4739, 0.5404],
        [0.0883, 0.3007, 0.5563, 0.3576]])


In [17]:
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[0.0834, 0.1517, 0.1789, 0.3919],
        [0.3443, 0.8042, 0.9021, 0.1086],
        [0.6852, 0.9519, 0.9372, 0.4315],
        [0.8652, 0.7995, 0.8361, 0.1026]])
tensor([[0.4698, 0.0681, 0.7762, 0.8819],
        [0.0315, 0.6252, 0.0229, 0.3498],
        [0.1974, 0.3786, 0.4739, 0.5404],
        [0.0883, 0.3007, 0.5563, 0.3576]])


**z1, z2, and z3 are mathematically equivalent operations**

### Aggregate all values of a tensor into one value

In [18]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(9.1502)
9.150201797485352 <class 'float'>


### In-place operations

In [19]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.6854, 0.2610, 0.8810, 0.9391],
        [0.1775, 0.7907, 0.1515, 0.5915],
        [0.4443, 0.6153, 0.6884, 0.7351],
        [0.2971, 0.5484, 0.7459, 0.5980]]) 

tensor([[5.6854, 5.2610, 5.8810, 5.9391],
        [5.1775, 5.7907, 5.1515, 5.5915],
        [5.4443, 5.6153, 5.6884, 5.7351],
        [5.2971, 5.5484, 5.7459, 5.5980]])


## Bridge tensor with NumPy

In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [21]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**there was an immediate change in n because t and n share memory**

In [22]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [23]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**there was an immediate change in t because t and n share memory**