In [1]:
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

## Create a tensor directly from a datalist

In [2]:
data = [[1,2],[3,4]]
data_tensor = torch.tensor(data)

print(data_tensor)

tensor([[1, 2],
        [3, 4]])


## Create a tensor from a NumPy array

In [3]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)

print(data_tensor)

tensor([[5, 6],
        [7, 8]], dtype=torch.int32)


## Create a tensor with same properties (shape, datatype) of an argument tensor

In [4]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)


# A tensor of the same shape as data_tensor with a 1 as every element
ones_tensor = torch.ones_like(data_tensor) # retains the properties of x_data
print(f"Ones Tensor: \n {ones_tensor} \n")

# A tensor of the same shape as data_tensor with a random number as every element
random_tensor = torch.rand_like(data_tensor, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {random_tensor} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]], dtype=torch.int32) 

Random Tensor: 
 tensor([[0.3498, 0.6756],
        [0.9089, 0.0811]]) 



## Create a tensor with random or constant values

In [5]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2965, 0.8096, 0.4676],
        [0.5550, 0.5837, 0.2491]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Commands to see tensor attributes

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Commands to move tensor to GPU

In [7]:
tensor = torch.rand(3,4)

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


## Indexing/Slicing commands

In [8]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
print(tensor)

tensor[:,1] = 0
print(tensor)

First row: tensor([0.8040, 0.6621, 0.7070, 0.8281])
First column: tensor([0.8040, 0.0897, 0.7204, 0.5998])
Last column: tensor([0.8281, 0.0015, 0.2047, 0.3415])
tensor([[0.8040, 0.6621, 0.7070, 0.8281],
        [0.0897, 0.3181, 0.4946, 0.0015],
        [0.7204, 0.0140, 0.1887, 0.2047],
        [0.5998, 0.9664, 0.4945, 0.3415]])
tensor([[0.8040, 0.0000, 0.7070, 0.8281],
        [0.0897, 0.0000, 0.4946, 0.0015],
        [0.7204, 0.0000, 0.1887, 0.2047],
        [0.5998, 0.0000, 0.4945, 0.3415]])


## Concatenate tensors

In [9]:
tensor1 = torch.tensor([[1,1],[1,1]])
tensor2 = torch.tensor([[2,2],[2,2]])
print(tensor1)
print(tensor2)

#concatenate tensors along the rows (it stacks them vertically)
tensor4x2 = torch.cat([tensor1,tensor2], dim=0)
print(tensor4x2)

#concatenate tensors along the columns (combine them horizontally)
tensor2x4 = torch.cat([tensor1,tensor2], dim=1)
print(tensor2x4)

tensor([[1, 1],
        [1, 1]])
tensor([[2, 2],
        [2, 2]])
tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2]])
tensor([[1, 1, 2, 2],
        [1, 1, 2, 2]])


## Operations on tensors

### Matrix multiplication between tensor and its transpose

In [10]:
tensor = torch.rand(4, 4)
print(tensor)

tensor([[0.7946, 0.9269, 0.0680, 0.6124],
        [0.6958, 0.5070, 0.6627, 0.3212],
        [0.0978, 0.3712, 0.2134, 0.1978],
        [0.4579, 0.2967, 0.6625, 0.5410]])


In [18]:
transpose_tensor = tensor.T
print(transpose_tensor)

tensor([[0.2002, 0.4514, 0.5444, 0.7513],
        [0.9484, 0.7454, 0.3250, 0.7731],
        [0.7426, 0.2943, 0.5628, 0.0184],
        [0.7168, 0.9783, 0.4145, 0.9788]])


In [19]:
y1 = tensor @ transpose_tensor
print(y1)

tensor([[2.0048, 1.7171, 1.1323, 1.5989],
        [1.7171, 1.8030, 1.0591, 1.8784],
        [1.1323, 1.0591, 0.8905, 1.0763],
        [1.5989, 1.8784, 1.0763, 2.1205]])


In [20]:
y2 = tensor.matmul(tensor.T)
print(y2)

tensor([[2.0048, 1.7171, 1.1323, 1.5989],
        [1.7171, 1.8030, 1.0591, 1.8784],
        [1.1323, 1.0591, 0.8905, 1.0763],
        [1.5989, 1.8784, 1.0763, 2.1205]])


In [23]:
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[0.2065, 0.4963, 0.4857, 0.7954],
        [0.1232, 0.1580, 0.2984, 0.7954],
        [0.4056, 0.4758, 0.2849, 0.5338],
        [0.4144, 0.3400, 0.8985, 0.3750]])
tensor([[2.0048, 1.7171, 1.1323, 1.5989],
        [1.7171, 1.8030, 1.0591, 1.8784],
        [1.1323, 1.0591, 0.8905, 1.0763],
        [1.5989, 1.8784, 1.0763, 2.1205]])


**y1, y2, and y3 are mathematically equivalent operations**

### Element-wise product between tensor and itself

In [12]:
print(tensor)
z1 = tensor * tensor
print(z1)

tensor([[0.7946, 0.9269, 0.0680, 0.6124],
        [0.6958, 0.5070, 0.6627, 0.3212],
        [0.0978, 0.3712, 0.2134, 0.1978],
        [0.4579, 0.2967, 0.6625, 0.5410]])
tensor([[0.6313, 0.8591, 0.0046, 0.3750],
        [0.4841, 0.2570, 0.4392, 0.1032],
        [0.0096, 0.1378, 0.0455, 0.0391],
        [0.2097, 0.0880, 0.4389, 0.2927]])


In [13]:
z2 = tensor.mul(tensor)
print(z2)

tensor([[0.6313, 0.8591, 0.0046, 0.3750],
        [0.4841, 0.2570, 0.4392, 0.1032],
        [0.0096, 0.1378, 0.0455, 0.0391],
        [0.2097, 0.0880, 0.4389, 0.2927]])


In [14]:
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[0.1709, 0.7444, 0.0847, 0.4341],
        [0.9698, 0.6250, 0.5601, 0.4698],
        [0.3236, 0.0618, 0.4759, 0.9792],
        [0.1131, 0.0606, 0.4286, 0.0376]])
tensor([[0.6313, 0.8591, 0.0046, 0.3750],
        [0.4841, 0.2570, 0.4392, 0.1032],
        [0.0096, 0.1378, 0.0455, 0.0391],
        [0.2097, 0.0880, 0.4389, 0.2927]])


**z1, z2, and z3 are mathematically equivalent operations**

### Aggregate all values of a tensor into one value

In [17]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(7.4266)
7.426631450653076 <class 'float'>


### In-place operations

In [18]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.7946, 0.9269, 0.0680, 0.6124],
        [0.6958, 0.5070, 0.6627, 0.3212],
        [0.0978, 0.3712, 0.2134, 0.1978],
        [0.4579, 0.2967, 0.6625, 0.5410]]) 

tensor([[5.7946, 5.9269, 5.0680, 5.6124],
        [5.6958, 5.5070, 5.6627, 5.3212],
        [5.0978, 5.3712, 5.2134, 5.1978],
        [5.4579, 5.2967, 5.6625, 5.5410]])


## Bridge tensor with NumPy

In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [21]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**there was an immediate change in n because t and n share memory**

In [25]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [26]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**there was an immediate change in t because t and n share memory**