In [1]:
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [8]:
torch.cuda.is_available()

False

## Create a tensor directly from a datalist

In [2]:
data = [[1,2],[3,4]]
data_tensor = torch.tensor(data)

print(data_tensor)

tensor([[1, 2],
        [3, 4]])


## Create a tensor from a NumPy array

In [3]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)

print(data_tensor)

tensor([[5, 6],
        [7, 8]])


## Create a tensor with same properties (shape, datatype) of an argument tensor

In [4]:
data = [[5,6],[7,8]]
data_np = np.array(data)
data_tensor = torch.from_numpy(data_np)


# A tensor of the same shape as data_tensor with a 1 as every element
ones_tensor = torch.ones_like(data_tensor) # retains the properties of x_data
print(f"Ones Tensor: \n {ones_tensor} \n")

# A tensor of the same shape as data_tensor with a random number as every element
random_tensor = torch.rand_like(data_tensor, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {random_tensor} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6704, 0.1230],
        [0.6266, 0.3116]]) 



## Create a tensor with random or constant values

In [5]:
shape = (2,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8002, 0.5505, 0.7785],
        [0.1196, 0.4211, 0.6114]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Commands to see tensor attributes

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Commands to move tensor to GPU

In [9]:
tensor = torch.rand(3,4)

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


## Indexing/Slicing commands

In [10]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
print(tensor)

tensor[:,1] = 0
print(tensor)

First row: tensor([0.9996, 0.9452, 0.7560, 0.5307])
First column: tensor([0.9996, 0.0873, 0.3896, 0.2925])
Last column: tensor([0.5307, 0.5686, 0.0062, 0.5538])
tensor([[0.9996, 0.9452, 0.7560, 0.5307],
        [0.0873, 0.6181, 0.2150, 0.5686],
        [0.3896, 0.1612, 0.7583, 0.0062],
        [0.2925, 0.4397, 0.4465, 0.5538]])
tensor([[0.9996, 0.0000, 0.7560, 0.5307],
        [0.0873, 0.0000, 0.2150, 0.5686],
        [0.3896, 0.0000, 0.7583, 0.0062],
        [0.2925, 0.0000, 0.4465, 0.5538]])


## Concatenate tensors

In [11]:
tensor1 = torch.tensor([[1,1],[1,1]])
tensor2 = torch.tensor([[2,2],[2,2]])
print(tensor1)
print(tensor2)

#concatenate tensors along the rows (it stacks them vertically)
tensor4x2 = torch.cat([tensor1,tensor2], dim=0)
print(tensor4x2)

#concatenate tensors along the columns (combine them horizontally)
tensor2x4 = torch.cat([tensor1,tensor2], dim=1)
print(tensor2x4)

tensor([[1, 1],
        [1, 1]])
tensor([[2, 2],
        [2, 2]])
tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2]])
tensor([[1, 1, 2, 2],
        [1, 1, 2, 2]])


## Operations on tensors

### Matrix multiplication between tensor and its transpose

In [12]:
tensor = torch.rand(4, 4)
print(tensor)

tensor([[0.3367, 0.5888, 0.7416, 0.7297],
        [0.7814, 0.9890, 0.4161, 0.2927],
        [0.0141, 0.7746, 0.0998, 0.1926],
        [0.1805, 0.7644, 0.4311, 0.4892]])


In [13]:
transpose_tensor = tensor.T
print(transpose_tensor)

tensor([[0.3367, 0.7814, 0.0141, 0.1805],
        [0.5888, 0.9890, 0.7746, 0.7644],
        [0.7416, 0.4161, 0.0998, 0.4311],
        [0.7297, 0.2927, 0.1926, 0.4892]])


In [14]:
y1 = tensor @ transpose_tensor
print(y1)

tensor([[1.5425, 1.3676, 0.6754, 1.1875],
        [1.3676, 1.8475, 0.8751, 1.2196],
        [0.6754, 0.8751, 0.6473, 0.7319],
        [1.1875, 1.2196, 0.7319, 1.0420]])


In [15]:
y2 = tensor.matmul(tensor.T)
print(y2)

tensor([[1.5425, 1.3676, 0.6754, 1.1875],
        [1.3676, 1.8475, 0.8751, 1.2196],
        [0.6754, 0.8751, 0.6473, 0.7319],
        [1.1875, 1.2196, 0.7319, 1.0420]])


In [16]:
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[0.2246, 0.7478, 0.0179, 0.9751],
        [0.7025, 0.3036, 0.3399, 0.3934],
        [0.3413, 0.6446, 0.1575, 0.6432],
        [0.6742, 0.1274, 0.7348, 0.3538]])
tensor([[1.5425, 1.3676, 0.6754, 1.1875],
        [1.3676, 1.8475, 0.8751, 1.2196],
        [0.6754, 0.8751, 0.6473, 0.7319],
        [1.1875, 1.2196, 0.7319, 1.0420]])


**y1, y2, and y3 are mathematically equivalent operations**

### Element-wise product between tensor and itself

In [17]:
print(tensor)
z1 = tensor * tensor
print(z1)

tensor([[0.3367, 0.5888, 0.7416, 0.7297],
        [0.7814, 0.9890, 0.4161, 0.2927],
        [0.0141, 0.7746, 0.0998, 0.1926],
        [0.1805, 0.7644, 0.4311, 0.4892]])
tensor([[1.1340e-01, 3.4674e-01, 5.4991e-01, 5.3243e-01],
        [6.1056e-01, 9.7817e-01, 1.7311e-01, 8.5672e-02],
        [1.9947e-04, 6.0008e-01, 9.9516e-03, 3.7092e-02],
        [3.2595e-02, 5.8428e-01, 1.8584e-01, 2.3933e-01]])


In [18]:
z2 = tensor.mul(tensor)
print(z2)

tensor([[1.1340e-01, 3.4674e-01, 5.4991e-01, 5.3243e-01],
        [6.1056e-01, 9.7817e-01, 1.7311e-01, 8.5672e-02],
        [1.9947e-04, 6.0008e-01, 9.9516e-03, 3.7092e-02],
        [3.2595e-02, 5.8428e-01, 1.8584e-01, 2.3933e-01]])


In [19]:
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[0.0796, 0.8529, 0.4594, 0.4997],
        [0.7143, 0.2360, 0.6242, 0.9845],
        [0.2838, 0.3852, 0.9867, 0.7183],
        [0.7472, 0.0591, 0.6307, 0.2630]])
tensor([[1.1340e-01, 3.4674e-01, 5.4991e-01, 5.3243e-01],
        [6.1056e-01, 9.7817e-01, 1.7311e-01, 8.5672e-02],
        [1.9947e-04, 6.0008e-01, 9.9516e-03, 3.7092e-02],
        [3.2595e-02, 5.8428e-01, 1.8584e-01, 2.3933e-01]])


**z1, z2, and z3 are mathematically equivalent operations**

### Aggregate all values of a tensor into one value

In [20]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(7.8223)
7.822348594665527 <class 'float'>


### In-place operations

In [21]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.3367, 0.5888, 0.7416, 0.7297],
        [0.7814, 0.9890, 0.4161, 0.2927],
        [0.0141, 0.7746, 0.0998, 0.1926],
        [0.1805, 0.7644, 0.4311, 0.4892]]) 

tensor([[5.3367, 5.5888, 5.7416, 5.7297],
        [5.7814, 5.9890, 5.4161, 5.2927],
        [5.0141, 5.7746, 5.0998, 5.1926],
        [5.1805, 5.7644, 5.4311, 5.4892]])


## Bridge tensor with NumPy

In [22]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [23]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**there was an immediate change in n because t and n share memory**

In [24]:
n = np.ones(5)
print(f"n: {n}")
t = torch.from_numpy(n)
print(f"t: {t}")

n: [1. 1. 1. 1. 1.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [25]:
np.add(n, 1, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**there was an immediate change in t because t and n share memory**